name: wordshk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  archive: ^3.1.6
  flutter:
    sdk: flutter

  flutter_rust_bridge: ^1.6.0
  http: ^0.13.4
  path_provider: ^2.0.7
  sum_types: ^0.3.0

  flutter_launcher_icons:
   git:
    url: https://github.com/dirkbo/flutter_launcher_icons.git
    ref: 5281519dd71aac8e5f37ebc0fe44b994677b567f

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  macos: true
  image_path: "assets/logo.png"
